const SET_TOKEN = 'SET_TOKEN';
const SET_USERS = 'SET_USERS';
const ADD_USER = 'ADD_USER';
const UPDATE_USER = 'UPDATE_USER';
const REMOVE_USER = 'REMOVE_USER';
const SET_PAGINATION = 'SET_PAGINATION';

export {
  SET_TOKEN,
  SET_USERS,
  ADD_USER,
  UPDATE_USER,
  REMOVE_USER,
  SET_PAGINATION,
};
